export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const REACHES_BOTTOM = 'REACHES_BOTTOM';
export const LEAVES_BOTTOM = 'LEAVES_BOTTOM';
export const ALL_ARTICLES_RECEIVED = 'ALL_ARTICLES_RECEIVED';